import 'package:hive/hive.dart';

part 'archive_item.g.dart';

@HiveType(typeId: 0)
class ArchiveItem extends HiveObject {
  @HiveField(0)
  final String date;

  @HiveField(1)
  final String concern;

  @HiveField(2)
  final String decision;

  @HiveField(3)
  final int severity;

  @HiveField(4)
  bool isSolved;

  // List to store retrospective notes or user comments
  @HiveField(5)
  List<String> comments; 

  // List to store the check status (true/false) of each action step
  @HiveField(6)
  List<bool> todoStatus;

  // [Added] List to store the actual text of action steps generated by Gemini
  @HiveField(7)
  final List<String> todoTasks;

  // [Added] List to store the timeline data (time and description pairs)
  @HiveField(8)
  final List<Map<String, String>> timeline;

  ArchiveItem({
    required this.date,
    required this.concern,
    required this.decision,
    required this.severity,
    required this.todoTasks, // Required to save specific tasks for each concern
    required this.timeline,  // Required to save specific timeline for each concern
    this.isSolved = false,
    List<String>? comments,
    List<bool>? todoStatus,
  })  : comments = comments ?? [],
        // Automatically initialize todoStatus with 'false' based on todoTasks length
        todoStatus = todoStatus ?? List.filled(todoTasks.length, false);
}

